spring:
  application:
    name: roomieYA_backend

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:postgresql://database-1.cxyo0ake445v.us-east-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: software12345
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgres

  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: 8da294001@smtp-brevo.com
    password: Kvpd32QnZ0m8PSw4
    default-encoding: UTF-8
    from: 8da294001@smtp-brevo.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8081

  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics